// Generated by CoffeeScript 1.3.3
(function() {

  exports.log = function(msgColor, msg) {
    var colorCode, colorsANSI, i, _i, _ref;
    colorsANSI = [
      {
        text: 'black',
        code: '\x1b[30m'
      }, {
        text: 'red',
        code: '\x1b[31m'
      }, {
        text: 'green',
        code: '\x1b[32m'
      }, {
        text: 'yellow',
        code: '\x1b[33m'
      }, {
        text: 'blue',
        code: '\x1b[34m'
      }, {
        text: 'magenta',
        code: '\x1b[35m'
      }, {
        text: 'cyan',
        code: '\x1b[36m'
      }, {
        text: 'white',
        code: '\x1b[37m'
      }
    ];
    colorCode = '';
    for (i = _i = 0, _ref = colorsANSI.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (msgColor === colorsANSI[i].text) {
        colorCode = colorsANSI[i].code;
      }
    }
    return console.log(colorCode, msg, '\x1b[0m');
  };

}).call(this);
