// Generated by CoffeeScript 1.3.3
(function() {
  var colors, fs;

  fs = require('fs');

  colors = require('colors');

  exports.accounts = function(filePath) {
    var a, buffer, ins, temp, tempAccounts;
    tempAccounts = [];
    if (fs.exists(filePath) && fs.isFile(filePath)) {
      console.log('Loading user accounts...');
      ins = fs.open(filePath, 'r');
      a = 0;
      while (!ins.atEnd()) {
        buffer = ins.readLine();
        temp = buffer.split(/\s*,\s*/);
        tempAccounts[a] = {
          accountType: temp[0],
          loginID: temp[1],
          password: temp[2],
          siteName: temp[3]
        };
        ++a;
      }
      return tempAccounts;
    } else {
      return console.log('Could not load ' + filePath);
    }
  };

  exports.articles = function(filePath) {
    var a, articleStatus, buffer, firstLine, ins, temp, tempArticles;
    tempArticles = [];
    articleStatus = '';
    firstLine = false;
    if (fs.exists(filePath) && fs.isFile(filePath)) {
      console.log('Loading articles...');
      ins = fs.open(filePath, 'r');
      a = -1;
      while (!ins.atEnd()) {
        buffer = ins.readLine();
        temp = buffer.trim();
        if (temp === '#Title') {
          articleStatus = 'title';
          ++a;
          tempArticles[a] = {
            title: '',
            description: '',
            body: '',
            keywords: '',
            links: '',
            images: ''
          };
        } else if (temp === '#Body') {
          articleStatus = 'body';
          firstLine = true;
        } else if (temp === '#Keywords') {
          articleStatus = 'keywords';
        } else if (temp === '#Links') {
          articleStatus = 'links';
        } else if (temp === '#Images') {
          articleStatus = 'images';
        } else if (articleStatus === 'title') {
          tempArticles[a].title += temp;
        } else if (articleStatus === 'body') {
          if (firstLine && temp !== '') {
            tempArticles[a].description = temp + '<br>';
            firstLine = false;
          }
          tempArticles[a].body += temp + '<br>';
        } else if (articleStatus === 'keywords') {
          temp = buffer.split(/\s*,\s*/);
          tempArticles[a].keywords = temp;
        } else if (articleStatus === 'links') {
          temp = buffer.split(/\s*,\s*/);
          tempArticles[a].links = temp;
        } else if (articleStatus === 'images') {
          temp = buffer.split(/\s*,\s*/);
          tempArticles[a].images = temp;
        }
      }
      ins.close();
      a = 0;
      return tempArticles;
    } else {
      return console.log('Could not load ' + filePath);
    }
  };

  exports.indexers = function(filePath) {
    var a, buffer, i, ins, noIndexer, status, temp, tempIndexers, _i, _ref;
    tempIndexers = [];
    status = '';
    if (fs.exists(filePath) && fs.isFile(filePath)) {
      ins = fs.open(filePath, 'r');
      a = -1;
      while (!ins.atEnd()) {
        buffer = ins.readLine();
        temp = buffer.trim();
        if (temp === '#name#') {
          status = 'name';
          ++a;
          tempIndexers[a] = {
            name: '',
            username: '',
            password: '',
            status: ''
          };
        } else if (temp === '#username#') {
          status = 'username';
        } else if (temp === '#password#') {
          status = 'password';
        } else if (temp === '#status#') {
          status = 'status';
        } else if (status === 'name') {
          tempIndexers[a].name = temp;
        } else if (status === 'username') {
          tempIndexers[a].username = temp;
        } else if (status === 'password') {
          tempIndexers[a].password = temp;
        } else if (status === 'status') {
          tempIndexers[a].status = temp;
        }
      }
      ins.close();
      a = 0;
      noIndexer = true;
      for (i = _i = 0, _ref = tempIndexers.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (tempIndexers[i].status.toLowerCase() === 'ok') {
          if (noIndexer) {
            tempIndexers[0] = tempIndexers[i];
            noIndexer = false;
          }
        }
      }
      if (tempIndexers.length === 0) {
        tempIndexers[0].username === 'no accounts';
      }
      return tempIndexers[0];
    } else {
      return console.log('Could not load ' + filePath);
    }
  };

  exports.services = function(filePath) {
    var a, buffer, ins, status, temp, tempServices;
    tempServices = [];
    status = '';
    if (fs.exists(filePath) && fs.isFile(filePath)) {
      ins = fs.open(filePath, 'r');
      a = -1;
      while (!ins.atEnd()) {
        buffer = ins.readLine();
        temp = buffer.trim();
        if (temp === '#name#') {
          status = 'name';
          ++a;
          tempServices[a] = {
            name: '',
            status: ''
          };
        } else if (temp === '#status#') {
          status = 'status';
        } else if (status === 'name') {
          tempServices[a].name = temp;
        } else if (status === 'status') {
          tempServices[a].status = temp;
        }
      }
      ins.close();
      a = 0;
      return tempServices;
    } else {
      return console.log('Could not load ' + filePath);
    }
  };

}).call(this);
